version: '3.1'

services:

redis:
    image: 'redis:alpine'
    container_name: 'redis'

mysql:
    image: 'mysql:5.7'
    container_name: 'mysql'
    working_dir: /var/www/html
    restart: always
    volumes:
        - './backend:/var/www/html'
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=deliverytcc
        - MYSQL_USER=delivery
        - MYSQL_PASSWORD=delivery
    ports:
        - '8083:3306'

webserver:
    image: 'nginx:alpine'
    container_name: 'nginx'
    working_dir: /var/www/html
    volumes:
        - './backend:/var/www/html'
        - './backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
        - '8080:80'

php-fpm:
    build: backend/docker/php-fpm
    container_name: 'delivery.php'
    working_dir: /var/www/html
    volumes:
        - './backend:/var/www/html'
        - './backend/docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'

phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
        - 8086:80
    environment:
        - PMA_ARBITRARY=1

frontend:
    build: 
    context: ./frontend
    dockerfile: Dockerfile
    container_name: 'react-frontend'
    tty: true
    ports: 
    - 3000:3000
    working_dir: /app/frontend
    volumes:
    - .:/app/frontend

#Developed by vinicius_ponce
